### PR TITLE
Added foursum an important question

### PR DESCRIPTION
**Pull request by Akriti-05**
contributing in hacktoberfest2021 
Added four_sum an important question in java.
Please accept or add label hacktoberfest-accepted
Thankyou!!

### CODE REVIEW

**Comment by Akriti-05** [comment]
Sorry the earlier file was empty, please consider the updated one!!

**Comment by MaitriGurey** [comment]
Please provide a question link or the question statement in the description.

**Comment by Akriti-05** [comment]
Sure!!

**Comment by Akriti-05** [comment]
Given an array nums of n integers, return an array of all the unique quadruplets [nums[a], nums[b], nums[c], nums[d]] such that:

0 <= a, b, c, d < n
a, b, c, and d are distinct.
nums[a] + nums[b] + nums[c] + nums[d] == target
You may return the answer in any order.

 

Example 1:

Input: nums = [1,0,-1,0,-2,2], target = 0
Output: [[-2,-1,1,2],[-2,0,0,2],[-1,0,0,1]]

**Comment by MaitriGurey** [comment]
Thank you for your valuable contribution!

**Pull request merged**
